<!DOCTYPE html>
<html lang=pt>
	<head>
		<meta charset=utf-8>
		<title>Principal - Squille</title>

		<meta name=viewport content='width=device-width, min-width=360px, initial-scale=1.0'>
		<meta name=description content='Sistema de Gerenciamento de Conteúdos da Weblight'>
		<meta name=author content='Weblight'>
		
		<link href='http://static.squille.com/admin/global/css/xs/common.css' rel=stylesheet>
		<link href='http://static.squille.com/admin/global/css/xs/layout.css' rel=stylesheet>
		<link href='https://fonts.googleapis.com/css?family=Noticia+Text' rel=stylesheet>
		
		<script src='http://static.squille.com/admin/global/js/ckeditor/ckeditor.js' type='text/javascript'></script>
		<script src='http://static.squille.com/admin/global/js/ckeditor/config.js' type='text/javascript'></script>
		<script src='http://static.squille.com/admin/global/js/ckeditor/styles.js' type='text/javascript'></script>
		
		<script src='http://static.squille.com/admin/global/js/library.js' type='text/javascript'></script>
	</head>

	<body>
		<section id='menu-principal'>
			<?php $adm = \Admin\Domain\SessionDomain::readUser()?>
			<h1>
				<img alt='<?=$adm->name?> avatar' src='data:image/jpeg;base64,<?=base64_encode($adm->avatar)?>'>
				<span><?=$adm->name?></span>
			</h1>
			<nav>
				<ul>
					<li><a href='/admin/categories'>Categorias</a></li>
					<li><a href='/admin/contents'>Conteúdos</a></li>
					<li><a href='/admin/links'>Links</a></li>
					<li><a href='/admin/menus'>Menus</a></li>
					<li><a href='/admin/pages'>Páginas</a></li>
					<li><a href='/admin/files'>Arquivos</a></li>
				</ul>
			</nav>
		</section>
		<header class='barra-topo'>
			<a href=# id='expandir'>expandir</a>
			<h1><a href='/admin/'>Principal - Squille</a></h1>
			<a href='/admin/auth/logout' class='sair'>sair</a>
		</header>
		<div class='content'><?php $content->display()?></div>
	</body>
</html>