<?php
/**
 * Squille (https://github.com/jairhumberto/Squille)
 *
 * MIT License
 *
 * Copyright (c) 2017 Jair Humberto
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
?>
<!DOCTYPE html>
<html lang=pt>
    <head>
        <meta charset=utf-8>
        <title>Principal - Squille</title>

        <meta name=viewport content='width=device-width, min-width=360px, initial-scale=1.0'>
        <meta name=description content='Sistema de Gerenciamento de Conteúdos da Weblight'>
        <meta name=author content='Weblight'>

        <link href='http://static.squille.com/admin/global/css/xs/common.css' rel=stylesheet>
        <link href='http://static.squille.com/admin/global/css/xs/layout.css' rel=stylesheet>
        <link href='https://fonts.googleapis.com/css?family=Noticia+Text' rel=stylesheet>

        <script src='http://static.squille.com/admin/global/js/ckeditor/ckeditor.js' type='text/javascript'></script>
        <script src='http://static.squille.com/admin/global/js/ckeditor/config.js' type='text/javascript'></script>
        <script src='http://static.squille.com/admin/global/js/ckeditor/styles.js' type='text/javascript'></script>

        <script src='http://static.squille.com/admin/global/js/library.js' type='text/javascript'></script>
    </head>

    <body>
        <section id='menu-principal'>
            <?php $adm = \Admin\Domain\SessionDomain::readUser()?>
            <h1>
                <img alt='<?=$adm->name?> avatar' src='data:image/jpeg;base64,<?=base64_encode($adm->avatar)?>'>
                <span><?=$adm->name?></span>
            </h1>
            <nav>
                <ul>
                    <li><a href='/admin/categories'>Categorias</a></li>
                    <li><a href='/admin/contents'>Conteúdos</a></li>
                    <li><a href='/admin/links'>Links</a></li>
                    <li><a href='/admin/menus'>Menus</a></li>
                    <li><a href='/admin/pages'>Páginas</a></li>
                    <li><a href='/admin/files'>Arquivos</a></li>
                </ul>
            </nav>
        </section>
        <header class='barra-topo'>
            <a href=# id='expandir'>expandir</a>
            <h1><a href='/admin/'>Principal - Squille</a></h1>
            <a href='/admin/auth/logout' class='sair'>sair</a>
        </header>
        <div class='content'><?php $content->display()?></div>
    </body>
</html>
