<?php
/**
 * Squille (https://github.com/jairhumberto/Squille)
 *
 * MIT License
 *
 * Copyright (c) 2017 Jair Humberto
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
?>
<!DOCTYPE html>
<html lang=pt>
    <head>
        <meta charset=utf-8>
        <title>Squille</title>

        <meta name=viewport content='width=device-width, initial-scale=1.0'>
        <meta name=description content='Sistema de Gerenciamento de Conteúdos da Weblight'>
        <meta name=author content='Weblight'>

        <link href='/admin/app/css/xs/common.css' rel=stylesheet>
        <link href='/admin/app/css/xs/auth.css' rel=stylesheet>

    </head>

    <body>
        <header>
            <h1>Squille</h1>
        </header>
        <div class='auth'>
            <?php $content->display()?>
        </div>
    </body>

    <!-- Squille JS Library. -->
    <script src='/admin/app/js/library.js' type='text/javascript'></script>
    <!-- Squille JS Library. -->
</html>
