<!DOCTYPE html>
<html lang=pt>
	<head>
		<meta charset=utf-8>
		<title>Squille</title>

		<meta name=viewport content='width=device-width, initial-scale=1.0'>
		<meta name=description content='Sistema de Gerenciamento de Conteúdos da Weblight'>
		<meta name=author content='Weblight'>
		
		<link href='http://static.squille.com/admin/global/css/xs/common.css' rel=stylesheet>
		<link href='http://static.squille.com/admin/global/css/xs/auth.css' rel=stylesheet>
		
		<script src='http://static.squille.com/admin/global/js/library.js' type='text/javascript'></script>
	</head>

	<body>
		<header>
			<h1>Squille</h1>
		</header>
		<div class='auth'>
			<?php $content->display()?>
		</div>
	</body>
</html>