<?php
/**
 * Squille (https://github.com/jairhumberto/Squille)
 *
 * MIT License
 *
 * Copyright (c) 2017 Jair Humberto
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
?>
<?php $o = $model->readContentById($id) ?>
<h2>Conteúdos - Editar</h2>
<form action='/admin/contents/save' method=post>
    <input type=hidden value='<?=$o->id?>' name='id'>

    <?php $categories = $model->readCategories() ?>
    <label for='i_category'>Categoria</label>
    <select name='category' id='i_category'>
        <option value=''>Selecione...</option>
        <?php foreach($categories as $c): ?>
        <option value='<?=$c->id?>'
            <?php if ((!empty($_POST['category']) && $_POST['category'] == $c->id)
                      || (empty($_POST['category']) && $o->category == $c->id)) echo ' selected="selected"' ?>><?=$c->description?></option>
        <?php endforeach ?>
    </select><br>

    <label for='i_description'>Descrição</label>
    <input type=text value='<?=!empty($_POST['description']) ? $_POST['description'] : $o->description ?>' placeholder='Digite aqui' name='description' id='i_description'><br>

    <label for='i_date'>Data</label>
    <input type='datetime-local' size='16' value='<?=!empty($_POST['date']) ? $_POST['date'] : $o->date ?>' name='date' id='i_date'><br>

    <label for='i_text'>Texto</label>
    <div class='textarea'>
        <textarea placeholder='Digite aqui' class='ckeditor' name='text' id='i_text'><?=!empty($_POST['text']) ? $_POST['text'] : $o->text ?></textarea>
    </div>

    <div class='form-actions'>
        <a href=# onclick='enviar_form(this.parentNode.parentNode, "save", event)'>Salvar</a>
        <a href=# onclick='enviar_form(this.parentNode.parentNode, "savecontinue", event)'>Salvar e Continuar</a>
        <a href='/admin/contents'>Cancelar</a>
    </div>
</form>

<h2>Páginas</h2>
<?php $pc = $model->readPagesByContent($o->id) ?>
<form action='/admin/pages-contents' method=post>
    <div class='form-body'>
        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Página</th>
                    <th>Seção</th>
                    <th>Ordem</th>
                    <th>Componente</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody id='tbody'>
                <?php foreach($pc as $page): ?>
                <tr>
                    <td><?=$page->id?></td>
                    <td><?=$page->page ? $model->readPageById($page->page)->title : 'Todas'?></td>
                    <td><?=$page->section?></td>
                    <td><?=$page->order?></td>
                    <td><?=$page->component?></td>
                    <td>
                        <a href='#' onclick='remove_page(this.parentNode.parentNode, "/admin/pages-contents/unbind/<?=$page->id?>", event)'>Excluir</a>
                    </td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>

        <br>

        <div class='form-actions'>
            <a href='#' onclick='add_row(document.getElementById("tbody"), event)'>Adicionar</a>
        </div>
    </div>
</form>

<!-- Table row. -->
<template id='page'>
    <tr>
        <td>#</td>
        
        <td>
            <input type='hidden' name='content' value='<?=$o->id?>'/>
            <input type='checkbox' name='todas' value='1' title='todas'/>
            <select name='page' onchange='fill_section_component(this, "contents")'>
                <option value=''>Selecione...</option>
                <?php $pages = $model->readPages() ?>
                <?php foreach($pages as $page): ?>
                    <option value='<?=$page->id?>'><?=$page->title?></option>
                <?php endforeach ?>
            </select>
        </td>
        
        <td class='section'>
            <select name='section' disabled>
                <option value=''>Selecione...</option>
            </select>
        </td>
        
        <td>
            <input name='order'/>
        </td>
        
        <td class='component'>
            <select name='component' disabled>
                <option value=''>Selecione...</option>
            </select>
        </td>
        
        <td>
            <a href='#' onclick='save_page(this.parentNode.parentNode, "contents", event)'>Salvar</a>
            <a href='#' onclick='remove_row(this.parentNode.parentNode, event)'>Excluir</a>
        </td>
    </tr>
</template>
<!-- Table row. -->
