<?php $o = $model->readContentById($id) ?>
<h2>Conteúdos - Editar</h2>
<form action='/admin/contents/save' method=post>
	<input type=hidden value='<?=$o->id?>' name='id'>
	
	<?php $categories = $model->readCategories() ?>
	<label for='i_category'>Categoria</label>
	<select name='category' id='i_category'>
		<option value=''>Selecione...</option>
		<?php foreach($categories as $c): ?>
		<option value='<?=$c->id?>'
			<?php if ((!empty($_POST['category']) && $_POST['category'] == $c->id)
					  || (empty($_POST['category']) && $o->category == $c->id)) echo ' selected="selected"' ?>><?=$c->description?></option>
		<?php endforeach ?>
	</select><br>
	
	<label for='i_description'>Descrição</label>
	<input type=text value='<?=!empty($_POST['description']) ? $_POST['description'] : $o->description ?>' placeholder='Digite aqui' name='description' id='i_description'><br>
	
	<label for='i_date'>Data</label>
	<input type='datetime-local' size='16' value='<?=!empty($_POST['date']) ? $_POST['date'] : $o->date ?>' name='date' id='i_date'><br>
	
	<label for='i_text'>Texto</label>
	<div class='textarea'>
		<textarea placeholder='Digite aqui' class='ckeditor' name='text' id='i_text'><?=!empty($_POST['text']) ? $_POST['text'] : $o->text ?></textarea>
	</div>
	
	<div class='form-actions'>
		<a href=# onclick='enviar_form(this.parentNode.parentNode, "save", event)'>Salvar</a>
		<a href=# onclick='enviar_form(this.parentNode.parentNode, "savecontinue", event)'>Salvar e Continuar</a>
		<a href='/admin/contents'>Cancelar</a>
	</div>
</form>

<h2>Páginas</h2>
<form action='/admin/pages-contents/bind' method=post>
	<div class='form-body'>
		<table>
			<thead>
				<tr>
					<th width='2%'><input type=checkbox onchange='check_all(this)'></th>
					<th>Endereço</th>
					<th>Título</th>
					<th>Ordem</th>
					<th>Seção</th>
					<th>Componente</th>
					<th>Fixo</th>
				</tr>
			</thead>
			<tbody>
				<?php $c = $model->readPages() ?>
				<?php $l = $model->readPagesByContent($o->id) ?>
				
				<?php foreach($c as $key => $p): ?>
					<?php
						$checked = ' ';
						$r = null;

						foreach($l as $q)
						if ($p->id == $q->page) {
							$r = $q;
							$checked = ' checked';
							break;
						}
					?>
					<tr>
						<td><input type=checkbox value='<?=$r->id?>' name='id[<?=$key?>]'<?=$checked?>></td>
						
						<input type=hidden name='page[<?=$key?>]' value='<?=$p->id?>'>
						<input type=hidden name='content' value='<?=$o->id?>'>

						<td><?=$p->token ?></td>
						<td><?=$p->title ?></td>
						<td><input type=number name='order[<?=$key?>]' value='<?=$r->order?>'></td>

						<?php $sections = $model->readSectionByLayout($p->layout) ?>
						<td>
							<select name='section[<?=$key?>]'>
								<option value=''>Selecione...</option>
								<?php foreach($sections as $s): ?>
								<option value='<?=$s->name?>'
									<?php if ((!empty($_POST['section'][$r->id]) && $_POST['section'][$r->id] == $s->name) ||
											  (empty($_POST['section'][$r->id]) && $r->section == $s->name)) echo ' selected="selected"' ?>><?=$s->name?></option>
								<?php endforeach ?>
							</select>
						</td>
						
						<?php $components = $model->readComponentByLayout($p->layout) ?>
						<td>
							<select name='component[<?=$key?>]'>
								<option value=''>Selecione...</option>
								<?php foreach($components as $c): ?>
								<option value='<?=$c->name?>'
									<?php if ((!empty($_POST['component'][$r->id]) && $_POST['component'][$r->id] == $c->name)
											  || (empty($_POST['component'][$r->id]) && $r->component == $c->name)) echo ' selected="selected"' ?>><?=$c->name?></option>
								<?php endforeach ?>
							</select>
						</td>
						
						<td><input type=checkbox name='fixed[<?=$key?>]'<?php if ($o->fixed && $o->fixed == $r->id) echo ' checked'?>></td>
					</tr>
				<?php endforeach ?>
			</tbody>
		</table>
	</div>
	
	<div class='form-actions'>
		<a href=# onclick='enviar_form(this.parentNode.parentNode, "save", event)'>Salvar</a>
		<a href=# onclick='enviar_form(this.parentNode.parentNode, "savecontinue", event)'>Salvar e Continuar</a>
	</div>
</form>