<?php
/**
 * Squille (https://github.com/jairhumberto/Squille)
 *
 * MIT License
 *
 * Copyright (c) 2017 Jair Humberto
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
?>
<h2>Conteúdos</h2>
<div class='form-actions'>
    <a href='/admin/contents/add'>Adicionar</a>
</div>
<div class='grid'>
    <table>
        <thead>
            <tr>
                <th width='80'>#</th>
                <th width='80'>Editar</th>
                <th width='80'>Excluir</th>
                <th>Descrição</th>
                <th>Categoria</th>
                <th>Data</th>
            </tr>
        </thead>
        <tbody>
            <?php $c = $model->readContents() ?>
            <?php foreach($c as $o): ?>
            <tr>
                <td><?=$o->id ?></td>
                <td><a href='/admin/contents/edit/<?=$o->id?>'>Editar</a></td>
                <td><a href=# onclick='return conditional_redirect(event, "/admin/contents/delete/<?=$o->id?>", "Tem certeza de que quer excluir o conteúdo \"<?=$o->description?>\"?")'>Excluir</a></td>
                <td><?=$o->description?></td>

                <?php $ct = $model->readCategoryById($o->category) ?>
                <td><?=$ct->description?></td>
                <td><?=$o->date?></td>
            </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
