<h2>Categorias - Adicionar</h2>
<form action='/admin/categories/save' method=post>
	<label for='i_description'>Descrição</label>
	<input type=text value='<?=isset($_POST['description']) ? $_POST['description'] : ''?>' placeholder='Digite aqui' name='description' id='i_description'><br>
	<div class='form-actions'>
		<a href=# onclick='enviar_form(this.parentNode.parentNode, "save", event)'>Salvar</a>
		<a href=# onclick='enviar_form(this.parentNode.parentNode, "savecontinue", event)'>Salvar e Continuar</a>
		<a href='/admin/categories'>Cancelar</a>
	</div>
</form>