<?php
/**
 * Squille (https://github.com/jairhumberto/Squille)
 *
 * MIT License
 *
 * Copyright (c) 2017 Jair Humberto
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
?>
<?php $o = $model->readCategoryById($id) ?>
<h2>Categorias - Editar</h2>
<form action='/admin/categories/save' method=post>
    <input type=hidden value='<?=$o->id?>' name='id'>
    <label for='i_description'>Descrição</label>
    <input type=text value='<?=!empty($_POST['description']) ? $_POST['description'] : $o->description ?>' placeholder='Digite aqui' name='description' id='i_description'><br>

    <div class='form-actions'>
        <a href=# onclick='enviar_form(this.parentNode.parentNode, "save", event)'>Salvar</a>
        <a href=# onclick='enviar_form(this.parentNode.parentNode, "savecontinue", event)'>Salvar e Continuar</a>
        <a href='/admin/categories'>Cancelar</a>
    </div>
</form>

<h2>Páginas</h2>

<?php $c = $model->readPagesByCategory($o->id) ?>
<form action='/admin/pages-categories/bind' method=post>
    <div class='form-body'>
        <table>
            <thead>
                <tr>
                    <th>Página</th>
                    <th>Seção</th>
                    <th>Ordem</th>
                    <th>Componente</th>
                    <th>Limite</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($c as $pc): ?>
                <tr>
                    <td><select></select></td>
                    <td><select></select></td>
                    <td><input></td>
                    <td><select></select></td>
                    <td><input></td>
                </tr>
                <?php endforeach ?>
            </tbody>
        </table>

        <br>

        <div class='form-actions'>
            <a href='#'>Adicionar</a>
        </div>
    </div>
</form>
