<?php
/**
 * Squille (https://github.com/jairhumberto/Squille)
 *
 * MIT License
 *
 * Copyright (c) 2017 Jair Humberto
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
?>
<h2>Páginas - Adicionar</h2>
<form action='/admin/pages/save' method=post>
    <label for='i_token'>Endereço</label>
    <input type=text value='<?=isset($_POST['token']) ? $_POST['token'] : ''?>' placeholder='Digite aqui' name='token' id='i_token'><br>

    <?php $layouts = $model->readXSLLayouts() ?>
    <label for='i_layout'>Layout</label>
    <select name='layout' id='i_layout'>
        <option value=''>Selecione...</option>
        <?php foreach($layouts as $l): ?>
        <option value='<?=$l->name?>'
                <?php if (isset($_POST['layout']) && $_POST['layout'] == $l->name) echo ' selected="selected"' ?>><?=$l->name?></option>
        <?php endforeach ?>
    </select><br>

    <label for='i_title'>Título</label>
    <input type=text value='<?=isset($_POST['title']) ? $_POST['title'] : ''?>' placeholder='Digite aqui' name='title' id='i_title'><br>

    <div class='form-actions'>
        <a href=# onclick='enviar_form(this.parentNode.parentNode, "save", event)'>Salvar</a>
        <a href=# onclick='enviar_form(this.parentNode.parentNode, "savecontinue", event)'>Salvar e Continuar</a>
        <a href='/admin/pages'>Cancelar</a>
    </div>
</form>
