<?php $o = $model->readPageById($id) ?>
<h2>Páginas - Editar</h2>
<form action='/admin/pages/save' method=post>
	<input type=hidden value='<?=$o->id?>' name='id'>

	<label for='i_token'>Endereço</label>
	<input type=text value='<?=!empty($_POST['token']) ? $_POST['token'] : $o->token ?>' placeholder='Digite aqui' name='token' id='i_token'><br>
	
	<?php $layouts = $model->readXSLLayouts() ?>
	<label for='i_layout'>Layout</label>
	<select name='layout' id='i_layout'>
		<option value=''>Selecione...</option>
		<?php foreach($layouts as $l): ?>
		<option value='<?=$l->name?>'
			<?php if ((!empty($_POST['layout']) && $_POST['layout'] == $l->name)
					  || (empty($_POST['layout']) && $o->layout == $l->name)) echo ' selected="selected"' ?>><?=$l->name?></option>
		<?php endforeach ?>
	</select><br>
	
	<label for='i_title'>Título</label>
	<input type=text value='<?=!empty($_POST['title']) ? $_POST['title'] : $o->title ?>' placeholder='Digite aqui' name='title' id='i_title'><br>
	
	<div class='form-actions'>
		<a href=# onclick='enviar_form(this.parentNode.parentNode, "save", event)'>Salvar</a>
		<a href=# onclick='enviar_form(this.parentNode.parentNode, "savecontinue", event)'>Salvar e Continuar</a>
		<a href='/admin/pages'>Cancelar</a>
	</div>
</form>
