<?php
/**
 * Squille (https://github.com/jairhumberto/Squille)
 *
 * MIT License
 *
 * Copyright (c) 2017 Jair Humberto
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
?>
<h2>Administradores - Adicionar</h2>
<form action='/admin/administrators/save' enctype='multipart/form-data' method=post>
    <label for='i_name'>Nome</label>
    <input type=text value='<?=isset($_POST['name']) ? $_POST['name'] : ''?>' placeholder='Digite aqui' name='name' id='i_name'><br>

    <label for='i_email'>E-mail</label>
    <input type=email value='<?=isset($_POST['email']) ? $_POST['email'] : ''?>' placeholder='Digite aqui' name='email' id='i_email'><br>

    <label for='i_password'>Senha</label>
    <input type=password value='<?=isset($_POST['password']) ? $_POST['password'] : ''?>' placeholder='Digite aqui' name='password' id='i_password'><br>

    <label for='i_avatar'>Avatar</label>
    <input type=file name='avatar' id='i_avatar'><br>

    <div class='form-actions'>
        <a href=# onclick='enviar_form(this.parentNode.parentNode, "save", event)'>Salvar</a>
        <a href=# onclick='enviar_form(this.parentNode.parentNode, "savecontinue", event)'>Salvar e Continuar</a>
        <a href='/admin/administrators'>Cancelar</a>
    </div>
</form>
